version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/images_db
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=images_db
    volumes:
      - pgdata:/var/lib/postgresql/data

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"

volumes:
  pgdata:
version: "3.9"
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volums:
      - ./backend:/app
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
